### PR TITLE
Added headerContent to layout

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by lennym** [comment]
This feels way too specific to our particular implementation to be a generic component library.

We can already inject custom components and content into the header in implementations via the `propositionHeader` prop (see the prototype build for example). There's a case to be made that this could be _better_, but I don't think this particular way is likely to be good for anyone else, or indeed likely to not change as our implementation changes, and so I think that this is the wrong place for it.

**Comment by joefitter** [comment]
agree completely, but I _really_ don't like the way it currently works - https://github.com/UKHomeOffice/asl-prototypes/blob/master/pages/components/page.jsx#L9

**Comment by lennym** [comment]
That's cool, I don't _really_ like it either, I just inherited it from the govuk template. Let's fix it with a generic placeholder for an injected component though.

**Comment by lennym** [comment]
Actually, looking at the govuk template again, I didn't inherit it, I just wrote a crappy solution.

**Comment by joefitter** [comment]
👍

**Pull request merged**
